# Site settings
title: cacophony.io
header-img: img/home-bg.jpg
email: jeff@openinfrastructure.co
description: > # this means to ignore newlines until "baseurl:"
  Cacophony App
baseurl: ""
url: "http://www.cacophony.io"
twitter_username: "0xEFF"
github_username: cacophonyapp
facebook_username: 
linkedin_username: 

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
